dependencies:
- pandoc=2.11.0.4    
- r-base=3.6.1
- r-bigrquery=1.3.2
- r-data.table=1.12.8
- r-dbi=1.0.0
- r-dplyr=0.8.0.1
- r-gargle=0.5.0
- r-ggplot2=3.1.1
- r-glue=1.3.1
- r-hmisc=4.2_0
- r-knitr=1.22
- r-logging=0.10_108
- r-parsedate=1.2.0
- r-rmarkdown=1.12
- r-stringi=1.4.3
- r-vegawidget=0.2.1
